### ISSUE TITLE
Optional Javascript Callback

### ISSUE THREAD

**Issue by thezenmonkey** [UndefinedOffset/silverstripe-nocaptcha#10]
I've created fork, with an optional callback to be called when the Recaptcha is verifed (enable submit button, etc). If it's useful, I can conver to a PR https://github.com/thezenmonkey/silverstripe-nocaptcha

**Comment by UndefinedOffset** [comment]
Sure create a pull request and I'll merge it in. Have you tested it with multiple instances on a single page? I'm assuming you have?

**Comment by UndefinedOffset** [comment]
Does this solve your issue in #9?

**Comment by thezenmonkey** [comment]
Right now it will call the same function for all instances, not a problem if you're just enabling the submit button since theoritcally a Human for one form is a suman for all forms on the page.

**Comment by UndefinedOffset** [comment]
I think the easy way to adjust that, would be to have your data-callback attribute store the name of the callback to use. Then in your js changes have it use the value of data-callback instead of hard coding it to "verifyCallback". Could you try that and see if it works? If it does mind updating your pull request should happen automatically when you push to the branch your pull is based off of.

**Comment by thezenmonkey** [comment]
The big problem with that is that the callback function in the Recpatcha API requires a variable passed when initatiated via javascript, and not a string. Calling ```javascript window[field.getAttribute('data-callback')]``` didn't seem to cut it.

**Comment by UndefinedOffset** [comment]
Ya probably for the best, I'm going to close this and merge the pull request. More than likely only one call back is needed anyways.
