### ISSUE TITLE
Invisible captcha invalid form submission bug

### ISSUE THREAD

**Issue by 3Dgoo** [UndefinedOffset/silverstripe-nocaptcha#29]
When using the invisible captcha the form submits to the server even when JavaScript validation deems the form to be invalid.

On submission of a form, if the form is invalid and the form submission is blocked by JavaScript the invisible captcha will override this block, submit the form and cause the page to refresh.

To recreate this issue we can create a UserForm with a required text field and an invisible captcha. Without filling in the required text field submit the form. The JavaScript validation will block the form submission and display a requirement error message on the text field. A couple of seconds later the form will submit and the page will refresh.

**Comment by UndefinedOffset** [comment]
This is very likely related to how the the [listener is bound to the form](https://github.com/UndefinedOffset/silverstripe-nocaptcha/blob/master/javascript/NocaptchaField.js#L18-L24). The [listener](https://github.com/UndefinedOffset/silverstripe-nocaptcha/blob/master/javascript/NocaptchaField.js#L4-L8) is required for the invisible captcha because it does not automatically run, it may just need to be tweaked to account for jQuery validate which I believe userforms is using.

**Comment by UndefinedOffset** [comment]
Give master a try now and let me know if it's still not working, it seems to be for me with the changes in 2da0ab9
