### ISSUE TITLE
Configurations available for reCaptcha v3

### ISSUE THREAD

**Issue by jinjie** [UndefinedOffset/silverstripe-nocaptcha#77]
What are some of the options available to v3?

I am trying to change the badge to bottomleft and the default size but doesn't change anything. Flushed

```
UndefinedOffset\NoCaptcha\Forms\NocaptchaField:
  recaptcha_version: 3
  default_badge: "bottomleft"
  default_size: "compact"
```

**Comment by UndefinedOffset** [comment]
The Recaptcha v3 badge has very limited yaml options you can however also style the badge using css.

That said from what I'm seeing it does sound like the `bottomleft` (or `inline`) should work so that is likely a bug. As for size, the only option supported is `invisible` for v3. (See https://developers.google.com/recaptcha/docs/invisible#render_param)

**Comment by UndefinedOffset** [comment]
Based on some reading it looks and how the v3 system is implemented in this module the `default_badge` option is not supported. I'd recommend using CSS to move the badge.
