### ISSUE TITLE
Captcha Stuck After Click

### ISSUE THREAD

**Issue by thezenmonkey** [UndefinedOffset/silverstripe-nocaptcha#9]
I'm running the captcha module on SS3.1 and the latest Spam protection module and when you click on the check box, it gets stuck on the blue rotatiting circle. I don't see any error fired in javascript or PHP. The same thing happens using the testing keys

Pleass see http://oenogallery.com/artists/don-maynard/art/water-spout for refrence.

**Comment by UndefinedOffset** [comment]
My hunch is that it's something to do with how the lightbox is working on the page. It seems to be duplicating the html for the form. My guess is it's something to do with that. If I remove the ``display: none`` on the ``.morph-content`` css selector the recapcha instance works correctly. One thing you could try doing is moving the contents of the form to an iframe instead of being right in the dom (not ideal) given how the lightbox you are using works that's likely a solution. Other than that I'm not sure how you would solve that one. Maybe there is a setting for the lightbox that tells it not to duplicate the dom elements or something like that. Of course there is always the other option of looking for another lightbox again not ideal.

All in all my guess that the issue here is something to do with how the lightbox is duplicating the form in the dom.

**Comment by thezenmonkey** [comment]
Hmm, okay I'll try moving the form back to a CSS only modal. I only oved them to the other one for interface consistancy :)

**Comment by thezenmonkey** [comment]
The lightbox was causing the issue. Once I changed teh lightbox bax to the old style the multiple instances worked again.
